// $(document).ready(function(){
//     $("p").click(function(){
//       $(this).hide();
//     });
//   });隐藏
// 鼠标
// $("#p1").mouseenter(function(){
//     alert('您的鼠标移到了 id="p1" 的元素上!');
// });
// $("#p1").mousedown(function(){
//     alert("鼠标在该段落上按下！");
// });
// $("#p1").mouseup(function(){
//     alert("鼠标在段落上松开。");
// });
// 聚焦
// $("input").focus(function(){
//     $(this).css("background-color","#cccccc");
//   });
//   $("input").blur(function(){
//     $(this).css("background-color","#ffffff");
//   });